import Wrapper from "@/Components/wrapper/Wrapper";
import "./globals.css";

export const metadata = {
  title: "Music App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Wrapper>{children}</Wrapper>
      </body>
    </html>
  );
}
